# Generated by Django 4.0.4 on 2022-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('article', models.CharField(max_length=13)),
                ('state', models.CharField(max_length=13)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=1500)),
                ('image', models.BinaryField()),
            ],
        ),
    ]
