# Generated by Django 4.0.4 on 2022-05-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('article', models.CharField(max_length=13)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.state')),
            ],
        ),
    ]
