# Generated by Django 4.0.4 on 2022-05-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_state_technic_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technic',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
