# Generated by Django 4.0.4 on 2022-05-25 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_delete_person_alter_technic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technic',
            name='article',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='technic',
            name='price',
            field=models.IntegerField(blank=True, max_length=500000),
        ),
        migrations.AlterField(
            model_name='technic',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.state'),
        ),
    ]
